drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
drop table if exists RestaurantRec
drop table if exists WebsiteUser
