version: "3.1"
# https://docs.docker.com/compose/compose-file/

services:

  mysql:
    image: mysql:5.7.18
    container_name: sfu_yelp_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
     - "3306:3306"
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - sfu_yelp_mysql_data:/var/lib/mysql

volumes:
  sfu_yelp_mysql_data:
